# Generated by Django 5.2.8 on 2026-05-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('sales', 'Sales'), ('market', 'Marketing'), ('spex', 'SPEX')], db_index=True, default='sales', max_length=20),
        ),
    ]
