# Generated by Django 5.2.8 on 2026-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('sales', 'Sales'), ('speaker_sales', 'Speaker Sales'), ('spex', 'SpEx'), ('tele_market', 'Tele Marketing'), ('market_research', 'Market Research')], db_index=True, default='sales', max_length=20),
        ),
    ]
