# Generated by Django 5.2.8 on 2026-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='team',
            new_name='team_legacy',
        ),
    ]
