# Generated by Django 5.2.8 on 2026-05-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_team_user_team_legacy'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_legacy',
            field=models.CharField(blank=True, db_index=True, default='sales', max_length=20, null=True),
        ),
    ]
