# Generated by Django 5.2.8 on 2026-05-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_migrate_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_legacy',
        ),
    ]
