# Generated by Django 5.2.8 on 2026-05-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_status_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('market_research', 'Market Research'), ('spex', 'SpEx'), ('operations', 'Operations'), ('speaker_sales', 'Speaker Sales'), ('telemarketing', 'Telemarketing')], db_index=True, default='sales', max_length=20),
        ),
    ]
