# Generated by Django 5.2.8 on 2026-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team_lead',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
