# Generated by Django 5.2.8 on 2026-05-19 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mapped_lead',
            field=models.ForeignKey(blank=True, help_text='The specific team lead this user/member is mapped under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
