# Generated by Django 6.0.4 on 2026-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_otptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('market_research', 'Market Research'), ('spex', 'SpEx'), ('operations', 'Operations'), ('speaker_sales', 'Speaker Sales'), ('telemarketing', 'Telemarketing'), ('data_mining', 'Data Mining')], db_index=True, default='sales', max_length=20),
        ),
    ]
