# Generated by Django 6.0.4 on 2026-06-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customrole_user_custom_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrole',
            name='base_permission',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('market_research', 'Market Research'), ('spex', 'SpEx'), ('operations', 'Operations'), ('speaker_sales', 'Speaker Sales'), ('telemarketing', 'Telemarketing'), ('data_mining', 'Data Mining')], default='sales', help_text='Which system permission level this role inherits.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text='Optional display-only role label. Does not affect permissions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.customrole'),
        ),
    ]
