# Generated by Django 6.0.4 on 2026-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_seed_system_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrole',
            name='is_all_access',
            field=models.BooleanField(default=False, help_text='If True, grants full access to all modules.'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='Pre-seeded system role — cannot be deleted.'),
        ),
    ]
