// All fields from the Zoho form. ONLY ticket_number is required.
export const APP_FIELDS = [
  // ── Identifier (the only required field) ─────────────────────────
  { key: "ticket_number",         label: "Ticket Number",          required: true  },

  // ── MR Section ───────────────────────────────────────────────────
  { key: "purpose",               label: "Purpose",                required: false },
  { key: "link_url",              label: "Link URL",               required: false },
  { key: "linkedin_keywords",     label: "LinkedIn Keywords",      required: false },
  { key: "duplicate_tickets",     label: "Duplicate Tickets",      required: false },
  { key: "competitor_event_name", label: "Competitor Event Name",  required: false },
  { key: "organizer",             label: "Organizer",              required: false },
  { key: "event_month_year",      label: "Event Month/Year",       required: false, isDate: true },
  { key: "event_location",        label: "Event Location (City, Region)", required: false },
  { key: "relationship",          label: "Relationship (Direct/Indirect)", required: false },
  { key: "type_of_ticket",        label: "Type of Ticket",         required: false },
  { key: "priority",              label: "Priority",               required: false },
  { key: "estimate",              label: "Estimate",               required: false, isNumber: true },
  { key: "mr_comments",           label: "MR Comments",            required: false },
  { key: "assigned_mr",           label: "Assigned MR",            required: false, isUser: true },

  // ── DMD Section ──────────────────────────────────────────────────
  { key: "assign_name",           label: "Assign Name",            required: false, isUser: true },
  { key: "assign_date",           label: "Assign Date",            required: false, isDate: true },
  { key: "actual_number",         label: "Actual Number",          required: false, isNumber: true },
  { key: "new_contacts_created",  label: "New Contacts Created",   required: false, isNumber: true },
  { key: "source_spreadsheet_id", label: "Source_Spreadsheet_ID",  required: false },
  { key: "source_tab",            label: "Source_Tab",             required: false },
  { key: "source_row_number",     label: "Source_Row_Number",      required: false, isNumber: true },
  { key: "idempotency_key",       label: "Idempotency_Key",        required: false },
  { key: "ticket_type",           label: "Ticket Type",            required: false },
  { key: "complete_date",         label: "Complete Date",          required: false, isDate: true },
  { key: "hubspot_entry_date",    label: "HubSpot Entry Date",     required: false, isDate: true },
  { key: "mined_count",           label: "Mined Count",            required: false, isNumber: true },
  { key: "dm_comments",           label: "DM Comments",            required: false },
  { key: "assign_name_lx2",       label: "Assign Name (LX-2)",     required: false, isUser: true },
  { key: "actual_count_lx2",      label: "Actual Count (LX-2)",    required: false, isNumber: true },
  { key: "complete_date_lx2",     label: "Complete Date - LX2",    required: false, isDate: true },
  { key: "dm_comments_lx2",       label: "DM Comments (LX-2)",     required: false },

  // ── Optional system field ────────────────────────────────────────
  { key: "status",                label: "Status",                 required: false },
  { key: "modified_time",         label: "Modified Time (audit fallback)", required: false, isDate: true },
  { key: "external_id",           label: "Zoho ID (external_id)",  required: false },
];

// Auto-mapping aliases — keys MUST match APP_FIELDS keys
export const ALIAS_MAP = {
  ticket_number:         ["ticket number", "ticket no", "ticket#", "ticketnumber", "ticket_number", "tn"],
  purpose:               ["purpose", "ticket purpose"],
  link_url:              ["link url", "url", "link", "website", "link_url"],
  linkedin_keywords:     ["linkedin keywords", "linkedin", "li keywords", "linkedin_keywords"],
  duplicate_tickets:     ["duplicate tickets", "duplicates", "dupe tickets", "duplicate_tickets"],
  competitor_event_name: ["competitor event name", "competitor event", "competitor", "competitor_event_name"],
  organizer:             ["organizer", "organiser", "host"],
  event_month_year:      ["event month/year", "event month year", "event date", "event_month_year"],
  event_location:        ["event location", "location", "city region", "event location (city, region)", "event_location"],
  relationship:          ["relationship", "direct/indirect", "relationship (direct/indirect)", "rel"],
  type_of_ticket:        ["type of ticket", "ticket type (mr)", "type_of_ticket"],
  priority:              ["priority"],
  estimate:              ["estimate", "est"],
  mr_comments:           ["mr comments", "market research comments", "mr_comments"],
  assigned_mr:           ["assigned mr", "mr assignee", "market research user", "assigned_mr"],

  assign_name:           ["assign name", "dmd assignee", "data mining user", "assign_name"],
  assign_date:           ["assign date", "assigned date", "assign_date"],
  actual_number:         ["actual number", "actual_number"],
  new_contacts_created:  ["new contacts created", "new contacts", "new_contacts_created"],
  source_spreadsheet_id: ["source spreadsheet id", "spreadsheet id", "source_spreadsheet_id"],
  source_tab:            ["source tab", "tab", "source_tab"],
  source_row_number:     ["source row number", "source row", "source_row_number"],
  idempotency_key:       ["idempotency key", "idempotency_key", "dedup key"],
  ticket_type:           ["ticket type", "ticket type (dmd)", "ticket_type"],
  complete_date:         ["complete date", "completion date", "complete_date"],
  hubspot_entry_date:    ["hubspot entry date", "hubspot date", "hubspot_entry_date"],
  mined_count:           ["mined count", "mined_count"],
  dm_comments:           ["dm comments", "dmd comments", "data mining comments", "dm_comments"],
  assign_name_lx2:       ["assign name (lx-2)", "assign name lx2", "lx2 assignee", "assign_name_lx2"],
  actual_count_lx2:      ["actual count (lx-2)", "actual count lx2", "actual_count_lx2"],
  complete_date_lx2:     ["complete date - lx2", "complete date lx2", "complete_date_lx2"],
  dm_comments_lx2:       ["dm comments (lx-2)", "dm comments lx2", "dm_comments_lx2"],

  status:                ["status", "ticket status"],
  modified_time:         ["modified time", "modified_time", "updated at", "modified"],
  external_id:           ["zoho id", "zoho_id", "external id", "external_id", "id", "record id", "record_id"],
};
