# Generated by Django 5.2.8 on 2026-05-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_status_field'),
        ('historical_event_registry', '0002_eventeditionmetrics'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventeditionmetrics',
            name='unique_event_edition_metrics',
        ),
        migrations.RenameIndex(
            model_name='eventeditionmetrics',
            new_name='event_editi_event_c_5e5795_idx',
            old_name='eem_code_year_idx',
        ),
        migrations.AlterUniqueTogether(
            name='eventeditionmetrics',
            unique_together={('event', 'event_year')},
        ),
    ]
