# Generated by Django 6.0.4 on 2026-05-04 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sub_company', models.CharField(choices=[('Linq Conferences', 'Linq Conferences'), ('Linq Training', 'Linq Training'), ('Linq Summits', 'Linq Summits'), ('Linq Live', 'Linq Live')], default='Linq Conferences', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('event_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=500)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['event_code'], name='events_event_c_c62a30_idx'), models.Index(fields=['status'], name='events_status_8890b6_idx'), models.Index(fields=['event_date'], name='events_event_d_ec8074_idx')],
            },
        ),
    ]
