# Generated by Django 5.2.8 on 2026-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_sales_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expected_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
