# Generated by Django 5.2.8 on 2026-05-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_expected_revenue'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_status_8890b6_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
