# Generated by Django 5.2.8 on 2026-05-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_events_updated_1a904d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepting_web_bookings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='content_check',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='market_research_team',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='marketing_check',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='official_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='sales_check',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_sales_team',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='spex_team',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='tele_marketing_team',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
