# Generated by Django 5.2.8 on 2026-05-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_accepting_web_bookings_event_content_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Draft', max_length=20),
        ),
    ]
