# Generated by Django 5.2.8 on 2026-05-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_annualisation_event_branding_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='telemarketing_team',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
