# Generated by Django 5.2.8 on 2026-05-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_telemarketing_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
