# Generated by Django 5.2.8 on 2026-05-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_city_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sub_company',
        ),
    ]
