# Generated by Django 5.2.8 on 2026-05-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_sub_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Postponed', 'Postponed')], db_index=True, default='Draft', max_length=20),
        ),
    ]
