# Generated by Django 6.0.4 on 2026-05-04 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_event', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(db_index=True, max_length=50)),
                ('company_name_raw', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('position', models.CharField(blank=True, default='', max_length=150)),
                ('attendance', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('No-show', 'No-show'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20)),
                ('dietary_requirements', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegates', to='companies.company')),
                ('invoice', models.ForeignKey(db_column='invoice_number', on_delete=django.db.models.deletion.CASCADE, related_name='delegates', to='book_event.bookevent', to_field='invoice_number')),
            ],
            options={
                'db_table': 'book_delegates',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['invoice', 'email'], name='book_delega_invoice_3737aa_idx'), models.Index(fields=['event_code'], name='book_delega_event_c_49e2de_idx'), models.Index(fields=['email'], name='book_delega_email_04817b_idx'), models.Index(fields=['company'], name='book_delega_company_722a29_idx'), models.Index(fields=['attendance'], name='book_delega_attenda_062adf_idx')],
                'unique_together': {('invoice', 'email')},
            },
        ),
    ]
