# Generated by Django 5.2.8 on 2026-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_delegate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdelegate',
            name='delegate_number',
            field=models.IntegerField(default=1),
        ),
    ]
