# Generated by Django 5.2.8 on 2026-05-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_delegate', '0002_bookdelegate_delegate_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookdelegate',
            options={'ordering': ['invoice__invoice_number', 'first_name']},
        ),
    ]
