# Generated by Django 5.2.8 on 2026-05-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_delegate', '0007_alter_bookdelegate_invoice_db_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdelegate',
            name='add_ons',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookdelegate',
            name='delegate_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookdelegate',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookdelegate',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
