# Generated by Django 5.2.8 on 2026-05-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_delegate', '0008_bookdelegate_add_ons_bookdelegate_delegate_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdelegate',
            name='delegate_count',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=1),
        ),
    ]
