# Generated by Django 5.2.8 on 2026-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_delegate', '0009_alter_bookdelegate_delegate_count'),
        ('book_event', '0018_bookevent_edition'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdelegate',
            name='edition',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bookdelegate',
            index=models.Index(fields=['edition'], name='book_delega_edition_ae0a4d_idx'),
        ),
    ]
