# Generated by Django 5.2.8 on 2026-05-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesheetsource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Google Sheet Source', 'verbose_name_plural': 'Google Sheet Sources'},
        ),
        migrations.AlterModelOptions(
            name='reportdefinition',
            options={'ordering': ['name'], 'verbose_name': 'Report Definition'},
        ),
        migrations.AlterField(
            model_name='googlesheetsource',
            name='column_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='Map sheet column headers to CRM field names. e.g. {"Invoice No": "invoice_number"}'),
        ),
        migrations.AlterField(
            model_name='googlesheetsource',
            name='filter_config',
            field=models.JSONField(blank=True, default=dict, help_text='Default filter rules for this source'),
        ),
        migrations.AlterField(
            model_name='googlesheetsource',
            name='formula_config',
            field=models.JSONField(blank=True, default=dict, help_text='Formula definitions reproduced from Google Sheets'),
        ),
        migrations.AlterField(
            model_name='googlesheetsource',
            name='grouping_config',
            field=models.JSONField(blank=True, default=dict, help_text='Column grouping and aggregation config'),
        ),
        migrations.AlterField(
            model_name='googlesheetsource',
            name='sheet_id',
            field=models.CharField(help_text='Google Sheet ID extracted from URL, or the full URL itself', max_length=200),
        ),
        migrations.AlterField(
            model_name='googlesheetsource',
            name='sheet_url',
            field=models.URLField(blank=True, default='', help_text='Full Google Sheets URL (optional, for reference)'),
        ),
        migrations.AlterField(
            model_name='googlesheetsource',
            name='transformation_config',
            field=models.JSONField(blank=True, default=dict, help_text='Per-column transformation rules. e.g. {"Date": ["date_iso"], "Amount": ["strip_currency"]}'),
        ),
        migrations.AlterField(
            model_name='googlesheetsource',
            name='worksheet_name',
            field=models.CharField(default='Sheet1', help_text='Exact tab/worksheet name to read', max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='column_config',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of column definitions'),
        ),
        migrations.AlterField(
            model_name='reportrow',
            name='processed_data',
            field=models.JSONField(default=dict, help_text='After column mapping and transformations applied'),
        ),
        migrations.AlterField(
            model_name='reportrow',
            name='raw_data',
            field=models.JSONField(default=dict, help_text='Verbatim column data keyed by sheet header'),
        ),
        migrations.AlterField(
            model_name='reportrow',
            name='row_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of raw_data for change detection', max_length=64),
        ),
        migrations.AlterField(
            model_name='reportrow',
            name='row_number',
            field=models.PositiveIntegerField(default=0, help_text='Original row index in the sheet (1-based, after header)'),
        ),
    ]
