# Generated by Django 6.0.4 on 2026-06-01 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('event_code', models.CharField(db_index=True, max_length=50)),
                ('event_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('mr_submitted', 'MR Submitted'), ('dmd_in_progress', 'DMD In Progress'), ('completed', 'Completed'), ('returned', 'Returned')], db_index=True, default='draft', max_length=20)),
                ('purpose', models.CharField(max_length=255)),
                ('link_url', models.URLField(max_length=500)),
                ('linkedin_keywords', models.CharField(blank=True, default='', max_length=500)),
                ('duplicate_tickets', models.CharField(blank=True, default='', max_length=255)),
                ('competitor_event_name', models.CharField(blank=True, default='', max_length=255)),
                ('organizer', models.CharField(blank=True, default='', max_length=255)),
                ('event_month_year', models.DateField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, default='', max_length=255)),
                ('relationship', models.CharField(blank=True, choices=[('direct', 'Direct'), ('indirect', 'Indirect')], default='', max_length=20)),
                ('type_of_ticket', models.CharField(blank=True, default='', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('mr_comments', models.TextField(blank=True, default='')),
                ('dmd_ticket_number_ref', models.CharField(blank=True, default='', help_text='Optional DMD-entered tracking reference (separate from auto ticket_number)', max_length=100)),
                ('assign_date', models.DateField(blank=True, null=True)),
                ('actual_number', models.PositiveIntegerField(blank=True, null=True)),
                ('new_contacts_created', models.PositiveIntegerField(blank=True, null=True)),
                ('source_spreadsheet_id', models.CharField(blank=True, default='', max_length=200)),
                ('source_tab', models.CharField(blank=True, default='', max_length=100)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=100)),
                ('ticket_type', models.CharField(blank=True, default='', max_length=50)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('hubspot_entry_date', models.DateField(blank=True, null=True)),
                ('mined_count', models.PositiveIntegerField(blank=True, null=True)),
                ('dm_comments', models.TextField(blank=True, default='')),
                ('actual_count_lx2', models.PositiveIntegerField(blank=True, null=True)),
                ('complete_date_lx2', models.DateField(blank=True, null=True)),
                ('dm_comments_lx2', models.TextField(blank=True, default='')),
                ('mr_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dmd_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned_as_dmd', to=settings.AUTH_USER_MODEL)),
                ('assign_name_lx2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned_as_dmd_lx2', to=settings.AUTH_USER_MODEL)),
                ('assigned_mr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned_as_mr', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
                ('dmd_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_dmd_submitted', to=settings.AUTH_USER_MODEL)),
                ('mr_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_mr_submitted', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_returned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='tickets_status_fbbf05_idx'), models.Index(fields=['event_code'], name='tickets_event_c_eeaac7_idx'), models.Index(fields=['-created_at'], name='tickets_created_f26b3b_idx'), models.Index(fields=['updated_at'], name='tickets_updated_75edd1_idx')],
            },
        ),
    ]
