# Generated by Django 6.0.4 on 2026-06-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_central', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='dmd_ticket_number_ref',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='link_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
