# Generated by Django 6.0.4 on 2026-06-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_central', '0002_remove_ticket_dmd_ticket_number_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
