# Generated by Django 6.0.4 on 2026-06-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_central', '0003_alter_ticket_event_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('last_number', models.PositiveIntegerField(default=10000)),
                ('added_user_text', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket_sequences',
                'ordering': ['purpose_key'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='added_user_text',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Source system ID (Zoho) — for migrated records only', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assign_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assign_name_lx2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_mr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='link_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='relationship',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
