# Generated by Django 6.0.4 on 2026-05-04 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_code', models.CharField(db_index=True, max_length=50)),
                ('event_name', models.CharField(blank=True, default='', max_length=255)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('pre_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('AED', 'AED'), ('SGD', 'SGD'), ('INR', 'INR'), ('OTHER', 'OTHER')], default='USD', max_length=10)),
                ('ticket_tier', models.CharField(blank=True, default='', max_length=20)),
                ('delegate_count', models.PositiveIntegerField(default=1)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Free', 'Free')], db_index=True, default='Pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, default='', max_length=30)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='book_events_invoice_34e7f1_idx'), models.Index(fields=['event_code'], name='book_events_event_c_54558c_idx'), models.Index(fields=['payment_status'], name='book_events_payment_8a85a2_idx'), models.Index(fields=['contact_email'], name='book_events_contact_8fb72e_idx'), models.Index(fields=['company_name'], name='book_events_company_b756e4_idx'), models.Index(fields=['created_at'], name='book_events_created_5bcb47_idx')],
            },
        ),
    ]
