# Generated by Django 5.2.8 on 2026-05-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Stripe', 'Stripe'), ('Bank', 'Bank')], default='', max_length=30),
        ),
    ]
