# Generated by Django 5.2.8 on 2026-05-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0002_alter_bookevent_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_logs',
            },
        ),
    ]
