# Generated by Django 5.2.8 on 2026-05-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0004_synclog_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='synclog',
            name='last_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='synclog',
            name='records_synced',
            field=models.IntegerField(default=0),
        ),
    ]
