# Generated by Django 5.2.8 on 2026-05-06 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0005_synclog_error_message_synclog_last_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookevent',
            index=models.Index(fields=['updated_at'], name='book_events_updated_0733c3_idx'),
        ),
    ]
