# Generated by Django 5.2.8 on 2026-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0006_bookevent_book_events_updated_0733c3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='accounts_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bookevent',
            name='add_ons',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookevent',
            name='booking_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookevent',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookevent',
            name='paid_free',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
