# Generated by Django 5.2.8 on 2026-05-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0008_bookevent_parent_code_bookevent_payment_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookevent',
            name='pre_tax_amount',
        ),
        migrations.RemoveField(
            model_name='bookevent',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='bookevent',
            name='total_amount',
        ),
    ]
