# Generated by Django 5.2.8 on 2026-05-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0012_alter_bookevent_payment_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhooklog',
            new_name='webhook_log_status_58a1da_idx',
            old_name='wlog_status_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooklog',
            new_name='webhook_log_created_33987a_idx',
            old_name='wlog_created_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooklog',
            new_name='webhook_log_invoice_34654a_idx',
            old_name='wlog_invoice_idx',
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
