# Generated by Django 5.2.8 on 2026-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0014_payment_ticket_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookevent',
            new_name='book_events_ticket__b2a975_idx',
            old_name='book_events_ticket_tier_idx',
        ),
        migrations.RenameIndex(
            model_name='bookevent',
            new_name='book_events_paid_or_35d4f9_idx',
            old_name='book_events_paid_or_free_idx',
        ),
        migrations.AddField(
            model_name='bookevent',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
