# Generated by Django 5.2.8 on 2026-05-18 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0016_bookevent_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookevent',
            name='ticket_tier',
            field=models.CharField(blank=True, choices=[('SEB', 'SEB'), ('EB', 'EB'), ('Regular', 'Regular')], default='', max_length=50),
        ),
    ]
