# Generated by Django 5.2.8 on 2026-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0017_bookevent_updated_by_alter_bookevent_ticket_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='edition',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
