# Generated by Django 5.2.8 on 2026-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0018_bookevent_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Free', 'Free'), ('Credit Pending (Free)', 'Credit Pending (Free)'), ('Credit Pending (Paid)', 'Credit Pending (Paid)'), ('Credit Transferred', 'Credit Transferred'), ('Paid (Transferred)', 'Paid (Transferred)')], db_index=True, default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookevent',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Stripe', 'Stripe'), ('Bank', 'Bank')], default='', max_length=30),
        ),
    ]
