"""
book_event/models.py
─────────────────────
Invoice-level booking entity.

Design decisions:
- invoice_number is PRE-GENERATED by the website — never auto-created here.
- Payment status lives here; delegates inherit it at read-time via @property.
- Financial fields map exactly to the Zoho payload field names.
- sales_executive is auto-assigned based on event→user mapping.
"""
from django.conf import settings
from django.db import models
from django.utils import timezone


class BookEvent(models.Model):
    class PaymentStatus(models.TextChoices):
        PENDING   = "Pending",   "Pending"
        PAID      = "Paid",      "Paid"
        CANCELLED = "Cancelled", "Cancelled"
        REFUNDED  = "Refunded",  "Refunded"
        FREE      = "Free",      "Free"

    class PaymentType(models.TextChoices):
        STRIPE = "Stripe", "Stripe"
        BANK   = "Bank",   "Bank"

    class Currency(models.TextChoices):
        USD   = "USD",   "USD"
        GBP   = "GBP",   "GBP"
        EUR   = "EUR",   "EUR"
        AED   = "AED",   "AED"
        SGD   = "SGD",   "SGD"
        INR   = "INR",   "INR"
        OTHER = "OTHER", "OTHER"

    # ── Identifiers ────────────────────────────────────────────────────────────
    invoice_number  = models.CharField(max_length=100, unique=True, db_index=True)
    event_code      = models.CharField(max_length=50, db_index=True)
    event_name      = models.CharField(max_length=255, blank=True, default="")
    event_date      = models.DateField(null=True, blank=True)
    invoice_date    = models.DateField(null=True, blank=True)
    booking_code    = models.CharField(max_length=100, blank=True, default="")

    # ── Ownership ──────────────────────────────────────────────────────────────
    sales_executive = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="bookings",
    )
    team_leader = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="team_bookings",
    )

    # ── Company / contact (denormalised for fast table queries) ────────────────
    company_name  = models.CharField(max_length=255, blank=True, default="")
    contact_name  = models.CharField(max_length=255, blank=True, default="")
    contact_email = models.EmailField(blank=True, default="")
    contact_phone = models.CharField(max_length=50, blank=True, default="")
    accounts_contact_email = models.EmailField(blank=True, default="")

    # ── Financial (Zoho field mapping) ─────────────────────────────────────────

    discount       = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    currency       = models.CharField(max_length=10, choices=Currency.choices, default=Currency.USD)
    ticket_tier    = models.CharField(max_length=20, blank=True, default="")
    delegate_count = models.PositiveIntegerField(default=1)

    # ── Payment ────────────────────────────────────────────────────────────────
    payment_status = models.CharField(
        max_length=20, choices=PaymentStatus.choices,
        default=PaymentStatus.PENDING, db_index=True,
    )
    payment_date     = models.DateField(null=True, blank=True)
    payment_due_date = models.DateField(null=True, blank=True)
    payment_type = models.CharField(
        max_length=30, blank=True, default="",
        choices=PaymentType.choices,
    )
    paid_free = models.CharField(max_length=20, blank=True, default="")

    # ── Reference ──────────────────────────────────────────────────────────────
    reference   = models.CharField(max_length=100, blank=True, default="")
    parent_code = models.CharField(max_length=100, blank=True, default="")
    notes      = models.TextField(blank=True, default="")
    add_ons    = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "book_events"
        ordering = ["-created_at"]
        indexes  = [
            models.Index(fields=["invoice_number"]),
            models.Index(fields=["event_code"]),
            models.Index(fields=["payment_status"]),
            models.Index(fields=["contact_email"]),
            models.Index(fields=["company_name"]),
            models.Index(fields=["created_at"]),
            models.Index(fields=["updated_at"]),
        ]

    def __str__(self):
        return f"{self.invoice_number} — {self.event_code}"

    def save(self, *args, **kwargs):
        if not self.invoice_number:
            raise ValueError("invoice_number must be pre-generated by the website.")
        super().save(*args, **kwargs)

    @classmethod
    def auto_assign_sales(cls, event_code: str):
        """Return the first sales user assigned to this event_code."""
        from accounts.models import User
        return (
            User.objects
            .filter(role=User.Role.SALES, assigned_events__event_code=event_code)
            .first()
        )

class SyncLog(models.Model):
    class Status(models.TextChoices):
        SUCCESS = "success", "Success"
        FAILED  = "failed",  "Failed"

    dataset        = models.CharField(max_length=50, unique=True)
    last_synced_at = models.DateTimeField(null=True, blank=True)
    last_status    = models.CharField(max_length=20, choices=Status.choices, default=Status.SUCCESS)
    records_synced = models.IntegerField(default=0)
    error_message  = models.TextField(blank=True, default="")

    class Meta:
        db_table = "sync_logs"

    def __str__(self):
        return f"{self.dataset}: {self.last_status} ({self.records_synced} rows) at {self.last_synced_at}"
