# Generated by Django 5.2.8 on 2026-05-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='googlesheetsynclog',
            index=models.Index(fields=['status'], name='gs_logs_status_idx'),
        ),
    ]
