export const APP_FIELDS = [
  { key: "invoice_number",         label: "Invoice Number",   required: true  },
  { key: "event_code",             label: "Event Code",       required: true  },
  { key: "event_name",             label: "Event Name",       required: true  },
  { key: "booking_code",           label: "Booking Code",     required: true  },
  { key: "contact_name",           label: "Name",             required: true  },
  { key: "contact_email",          label: "Delegate Email",   required: true  },
  { key: "request_date",           label: "Request Date",     required: false, isDate: true  },
  { key: "invoice_date",           label: "Invoice Date",     required: false, isDate: true  },
  { key: "company_name",           label: "Delegate Company", required: false },
  { key: "contact_phone",          label: "Direct Line",      required: false },
  { key: "accounts_contact_email", label: "Accounts Contact", required: false },
  { key: "payment_status",         label: "Payment Status",   required: false },
  { key: "paid_or_free",           label: "Paid/Free",        required: false },
  { key: "payment_date",           label: "Date Paid",        required: false, isDate: true  },
  { key: "payment_type",           label: "Payment Type",     required: false },
  { key: "ticket_tier",            label: "Ticket Tier",      required: false },
  { key: "discount_code",          label: "Discount",         required: false },
  { key: "add_ons",                label: "Add-Ons",          required: false },
  { key: "reference",              label: "Ref",              required: false },
  { key: "sales_executive",        label: "Sales Executive",  required: false },
  { key: "attendance",             label: "Attendance",       required: false },
  { key: "created_at",             label: "Added Time",       required: false, isDate: true  },
  { key: "delegate_count",         label: "Delegate Count",   required: false },
];

// Alias dictionary for auto-mapping (key = app field key, value = array of aliases)
export const ALIAS_MAP = {
  invoice_number:         ["invoice number","invoice no","inv number","inv no","invoice #","invoice_number"],
  event_code:             ["event code","eventcode","evt code","event_code"],
  event_name:             ["event name","eventname","evt name","event title","event_name"],
  request_date:           ["request date","requestdate","req date","request_date"],
  invoice_date:           ["invoice date","invoicedate","inv date","invoice_date"],
  booking_code:           ["booking code","bookingcode","booking ref","booking reference","booking no","booking_code"],
  company_name:           ["company name","delegate company","company","organisation","organization","company_name"],
  contact_name:           ["name","contact name","full name","delegate name","person name","contact_name"],
  contact_email:          ["email","contact email","delegate email","email address","e-mail","contact_email"],
  contact_phone:          ["phone","contact phone","direct line","telephone","tel","mobile","contact_phone"],
  accounts_contact_email: ["accounts contact","accounts email","finance email","billing email","accounts_contact_email"],
  payment_status:         ["payment status","paymentstatus","pay status","payment_status"],
  paid_or_free:           ["paid/free","paid or free","paid free","paid_or_free"],
  payment_date:           ["date paid","payment date","paymentdate","pay date","paid date","payment_date"],
  payment_type:           ["payment type","paymenttype","pay type","payment method","payment_type"],
  ticket_tier:            ["ticket tier","tickettier","tier","ticket type","ticket_tier"],
  discount_code:          ["discount","discount code","promo code","coupon","discount_code"],
  add_ons:                ["add-ons","addons","extras","additional","add_ons"],
  reference:              ["ref","reference","ref no","reference number"],
  sales_executive:        ["sales executive","salesexecutive","sales rep","account manager","sales_executive"],
  attendance:             ["attendance","attendance in","attended","checked in","present"],
  created_at:             ["added time","created at","createdat","date added","timestamp","created_at"],
  delegate_count:         ["count of rows","delegate count","row count","total delegates","delegate_count"],
};
