# Generated by Django 5.2.8 on 2026-05-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhookapikey_webhooklog_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooklog',
            name='db_insert_status',
            field=models.CharField(blank=True, choices=[('inserted', 'Inserted'), ('updated', 'Updated'), ('duplicate', 'Duplicate'), ('failed', 'Failed'), ('partial', 'Partial')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], db_index=True, default='received', max_length=20),
        ),
    ]
